name: Suggest a game
description: Suggest a game to be added in Win7 Simu Online Games list.
labels: game
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a game to improve Win7 Simu!
        The suggested game will be added to the Online Games list in Win7 Simu as below:
        
        <img width="470" height="367" alt="Image" src="https://github.com/user-attachments/assets/49304c46-9d38-4b99-83a5-a80cdc9a1c1b" />
  - type: input
    id: url
    attributes:
      label: Game URL
      description: The URL of the web game
      placeholder: ex. https://my-web-game.com
    validations:
      required: true
  - type: input
    id: icon
    attributes:
      label: Game icon
      description: The URL of the game icon
      placeholder: ex. https://cdn.my-web-game.com/icon.png
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: Game title
      description: A user-friendly title of the game
      placeholder: ex. My Awesome Game
    validations:
      required: true
  - type: input
    id: creator
    attributes:
      label: Game creator
      description: Who made the game
    validations:
      required: true
  - type: checkboxes
    id: confirm
    attributes:
      label: Is the game URL able to load in the Iframe Tester (https://iframetester.com)?
      options:
        - label: Yes, I can confirm it can load in iframe
          required: true
